### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by MicheleMercuri** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#14]
Hi, I'm newbie, can you help me with this issue?
Integration error: kiosks - Integration 'kiosks' not found.
Integration error: name - Integration 'name' not found.
Invalid config for [sensor.fusion_solar_kiosk]: required key not provided @ data['kiosks']. Got None. (See ?, line ?).

i've changed link in the line 36 of the file /config/custom_components/fusion_solar_kiosk/sensor.py and in the sensor.py file with the new one but with no luck. 

Many, thanks

**Comment by varn-lt** [comment]
config in example is not valid
instead of:
```
sensor:
    - platform: fusion_solar_kiosk
    kiosks:
        - id: "XXXXX"
        name: "A readable name for the plant"
```
should be
```
sensor:
  - platform: fusion_solar_kiosk
    kiosks:
      id: "XXXXXX"
      name: "A readable name for the plant"
```
